FROM node:22-alpine AS builder

RUN addgroup -S appuser && adduser -S appuser -G appuser
USER appuser
WORKDIR /Frontend/h5/qdzy

COPY --chown=appuser:appuser .npmrc* ./
RUN corepack enable && corepack prepare pnpm@latest --activate

COPY --chown=appuser:appuser package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/home/appuser/.pnpm-store \
    pnpm install --frozen-lockfile --shamefully-hoist

COPY --chown=appuser:appuser . .
RUN pnpm quasar build

FROM nginxinc/nginx-unprivileged:1.25-alpine

COPY /Frontend/h5/qdzy/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder --chown=nginx:nginx /Frontend/h5/qdzy/dist/spa /usr/share/nginx/html

HEALTHCHECK --interval=30s --timeout=5s \
  CMD curl -f http://localhost/ || exit 1

EXPOSE 80