[package]
name = "ebike"
version = "0.1.0"
authors = ["CaNplay <canplay@vip.qq.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
log4rs = "*"
futures = "*"
actix-web = "*"
actix-cors = "*"
actix-identity = "*"
actix-session = { version = "*", features = ["cookie-session"] }
serde = "*"
serde_json = "*"
chrono = { version = "*", features = ["serde"] }
anyhow = "*"
reqwest = { version = "*", features = ["cookies", "gzip", "json"] }
uuid = { version = "*", features = ["v4"] }
blake2 = "*"
urlencoding= "*"
sqlx = { version = "*", features = [ "runtime-actix-native-tls", "postgres", "mysql", "chrono", "json", "decimal" ] }
openssl = { version = "*", features = ["vendored"] }
