export interface ShopResponse<T> {
  code: number
  siteProductList?: T[]
  siteFrontJson?: T
  msg: string
}

export interface ShopIndex {
  id: number
  siteId: number
  content: string
  createBy: number
  createDate: string
  updateBy: number
  updateDate: string
  remarks: string
  status: string
}

export interface ShopIndexItem {
  id: number
  productId: number
  productNo: string
  orgId: number
  siteId: number
  supplyPrice: number
  distribPrice: number
  markPrice: number
  salePrice: number
  profitPercent: number
  source: number
  operStatus: string
  status: string
  createBy: number
  createDate: string
  updateBy: number
  updateDate: string
  remarks: string
  isFront: string
  labelImg: string
  moneyMode: number
  pricePoints: string
  priceMoney: number
  productType: number
  saleNumRecord: number
  fictitiousSaleNum: number
  ptPrice: number
  photo: string
  itemCode: string
  itemName: string
  supplyId: number
  supplyName: string
  itemCate: string
  itemCateName: string
  type: number
  content: string
  owner: string
  itemId: number
  salePoints: number
  markPoints: number
  supplyTitle: string
  sort: number
  items: string
  num: number
  advertPhoto: string
  seckillId: number
  preferentialPrice: number
  preferentialAmount: number
  limitMaxType: number
  limitMaxNum: number
  startTime: string
  endTime: string
  startTimeStamp: string
  endTimeStamp: string
  seckillOperStatus: number
  characteristic: number
  periods: number
  periodsName: string
  feePaytype: number
  productImageList: string
  limitNum: number
  productGiftList: string
  sortDate: string
  selfPick: number
  selfPickType: number
  combinationSalePrice: number
  subSiteProductDetailList: string
  isSpecification: number
  specification: string
  specificationValue: string
  productSpecifications: string
  specificationsList: string
  specProudctList: string
  field1: string
  field2: string
  field3: string
  jdNoReasonToReturn: number
  returnCompany: string
  advertId: number
  cid1: string
  cid2: string
  cid3: string
  lowestBuy: string
  checkWhiteSwitch: number
  showSupplyPrice: number
  showEnd: number
  seckillNum: number
  selfVoucherType: number
  selfSwitch: number
  leadDate: string
  selfStart: string
  selfEnd: string
  brandId: number
  brandName: string
  spuId: number
  saleAttr: string
  standCatId: number
  imagePath: string
  productExt: string
  isYx: number
  directType: number
  isShowMall: number
  crossedPrice: 44
  crossedPoint: 44
  citySend: number
  isShow: number
  freightRule: number
  checkRequired: number
  productPhotoUrl: string
}
